add polish language support
CovidEngine/vaxxnz pull request #148
Opened 2021-09-11 07:32 UTC by waltzaround

Adds polish language support courtesy of @MattOfNZ's polish friend

2021-09-11 07:50 UTC, olafwrieden requested changes
Some missing translations but otherwise looking fine :)

2021-09-11 07:50 UTC, olafwrieden commented on src/translations/locales/common_pl-PL.json
> +    "address": "Address"
Translation required.

2021-09-11 07:50 UTC, olafwrieden commented on src/translations/locales/common_pl-PL.json
> +    "unknownLocation": "Unknown Location"
Translation required.

2021-09-11 07:50 UTC, olafwrieden commented on src/translations/locales/common_pl-PL.json
> +        "message": "The information here may not be 100% accurate. Please refer to the location's website."
Translations required.

2021-09-11 07:50 UTC, olafwrieden commented on src/translations/locales/common_pl-PL.json
> +    "numberOfAppointments": "{{sumAvailableTimes}} available"
Translations required.

2021-09-11 07:50 UTC, olafwrieden commented on src/translations/locales/common_pl-PL.json
> +    "addressFinderLinkCopy": "Thanks to <0>AddressFinder</0> for free-of-charge address lookup"
Translation required.

2021-09-11 07:52 UTC, waltzaround commented
its coming @olafwrieden

2021-09-12 00:32 UTC, noway commented
@waltzaround have we got the changes

2021-09-12 02:42 UTC, waltzaround commented on src/translations/locales/common_pl-PL.json
> +    "address": "Address"
just added

2021-09-12 02:42 UTC, waltzaround commented on src/translations/locales/common_pl-PL.json
> +    "unknownLocation": "Unknown Location"
added

2021-09-12 02:42 UTC, waltzaround commented on src/translations/locales/common_pl-PL.json
> +        "message": "The information here may not be 100% accurate. Please refer to the location's website."
added

2021-09-12 02:42 UTC, waltzaround commented on src/translations/locales/common_pl-PL.json
> +    "numberOfAppointments": "{{sumAvailableTimes}} available"
added

2021-09-12 02:42 UTC, waltzaround commented on src/translations/locales/common_pl-PL.json
> +    "addressFinderLinkCopy": "Thanks to <0>AddressFinder</0> for free-of-charge address lookup"
added

2021-09-12 02:43 UTC, waltzaround reviewed
just came in fresh

2021-09-12 02:47 UTC, olafwrieden approved these changes

2021-09-12 02:47 UTC, merged

2021-09-12 02:47 UTC, noway reviewed
LGTM

2021-09-12 02:47 UTC, noway reviewed
LGTM