Add Hindi translations
CovidEngine/vaxxnz pull request #171
Opened 2021-09-12 09:23 UTC by waltzaround

Adds hindi translations

2021-09-12 09:34 UTC, noway requested changes
if we can add these missing ones, would be amazing. allg if not!

2021-09-12 09:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +    "numberOfAppointments": "{{sumAvailableTimes}} available",
this one missed 🙏🏻

2021-09-12 09:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +    "addressFinderLinkCopy": "Thanks to <0>AddressFinder</0> for free-of-charge address lookup",
This one missed too 🙏🏻

2021-09-12 09:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +      "roadmap": "Roadmap"
and these 3 🙏🏻

2021-09-12 09:35 UTC, olafwrieden commented
Please import and add locale to `locale.ts`

2021-09-12 10:31 UTC, noway commented
![image](https://user-images.githubusercontent.com/2031472/132984198-199f7713-3330-4524-9e4b-ce52a473958a.png)
Does this look all good or is it missing a space? Can a native speaker confirm.

2021-09-12 10:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +    "noResultsInRadius": "No vaccination sites found for this search query. Try a different kilometer radius."
This two are missing 🙏🏻

2021-09-12 10:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +    "openString": "Open {{openTimeString}}",
This one missing too 🙏🏻

2021-09-12 10:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +    "publicHolidays": "Public Holidays",
This one missing 🙏🏻

2021-09-12 10:34 UTC, noway commented on src/translations/locales/common_hi-HI.json
> +      "backToCalendar": "Back to Calendar"
this one 🙏🏻

2021-09-13 06:45 UTC, waltzaround commented
On standby until we get the remaining translations

2021-09-14 13:19 UTC, noway approved these changes
LGTM SHIP IT

2021-09-14 13:19 UTC, merged