added function for phone number parser and test
CovidEngine/vaxxnz pull request #227
Opened 2021-09-19 07:08 UTC by bookwyrm31415

## Proposed Changes
1.  Added a phone number parses in the utils folder, and a few tests for it

## Additional Info.
The parser function either returns a string of the phone number you can put in the href link or null if the string does not have a phone number in it

2021-09-19 22:54 UTC, noway commented
OMG, awesome!! I'll have a look tonight

2021-09-20 02:39 UTC, bookwyrm31415 commented
It's just a wrapper for a bunch of regex to handle all the edge cases on
the issue page.

I hope thats kind of what you wanted 🤷‍♂️

If not let me know and I can change it

On Mon, 20 Sep 2021, 10:54 Ilia Sidorenko, ***@***.***> wrote:

> OMG, awesome!! I'll have a look tonight
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CovidEngine/vaxxnz/pull/227#issuecomment-922549802>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM5P7RWY3L7SEMBWYU5X463UCZSZLANCNFSM5EKA25XQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-20 06:55 UTC, olafwrieden requested changes
@bookwyrm31415 I'd like to request small formatting changes. From an implementation point of view, are you able to implement your function on all the modals where phone numbers are displayed? We'd need that to ship this functionality and close the original issue. Love this!

2021-09-20 06:55 UTC, olafwrieden commented on src/utils/parsePhone.ts
> +
Please reduce the whitespace here, you can condense this to one line.

2021-09-20 06:55 UTC, olafwrieden commented on src/utils/parsePhone.spec.ts
> +
Reduce whitespace please, no need for blank lines in between. Tip: Also run prettier for formatting. We use an indentation of tab size: 2 throughout this project (not 4 spaces indentation) - Prettier should fix this for you.

2021-09-20 06:55 UTC, olafwrieden commented on src/utils/parsePhone.spec.ts
> +
Reduce whitespace please. Only add 1 blank line between test cases,

2021-09-20 06:55 UTC, olafwrieden commented on src/utils/parsePhone.ts
> +    //So I check its length and do an 0800 regex as well
Small ask to improve the comment, remember other people need to read this in the context of what the code does, not what you ("so _I_ check") do. Thanks!

2021-09-20 08:58 UTC, bookwyrm31415 commented
So sorry about all the intermediate commits, but this latest one passes the
checks

Regards
Ryan

On Mon, Sep 20, 2021 at 6:55 PM Olaf Wrieden ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @bookwyrm31415 <https://github.com/bookwyrm31415> I'd like to request
> small formatting changes. From an implementation point of view, are you
> able to implement your function on all the modals where phone numbers are
> displayed? We'd need that to ship this functionality and close the original
> issue. Love this!
> ------------------------------
>
> In src/utils/parsePhone.ts
> <https://github.com/CovidEngine/vaxxnz/pull/227#discussion_r711909557>:
>
> > +
> +
> +//Takes in a string and returns either the forst valid phone number or null
> +
>
> Please reduce the whitespace here, you can condense this to one line.
> ------------------------------
>
> In src/utils/parsePhone.spec.ts
> <https://github.com/CovidEngine/vaxxnz/pull/227#discussion_r711910234>:
>
> > +
> +        const want = "(07) 873 7079";
> +
> +        const got = parsePhoneNumber("{ telephone: '(07) 873 7079  /  A/H (07) 873 8399' }");
> +
>
> Reduce whitespace please, no need for blank lines in between. Tip: Also
> run prettier for formatting. We use an indentation of tab size: 2
> throughout this project (not 4 spaces indentation) - Prettier should fix
> this for you.
> ------------------------------
>
> In src/utils/parsePhone.spec.ts
> <https://github.com/CovidEngine/vaxxnz/pull/227#discussion_r711910492>:
>
> > +
> +
> +    it("should return a string of the 0800 number", () => {
> +
> +        const want = "0800 ORANGA";
> +
> +        const got = parsePhoneNumber("{ telephone: '0800 ORANGA (672 642)' }");
> +
> +        expect(got).toBe(want);
> +    })
> +
> +
> +
> +    it("should return a null", () => {
> +
> +        const want = null;
> +
> +        const got = parsePhoneNumber("test string no actual phone number");
> +
> +        expect(got).toBe(want);
> +    })
> +
> +
>
> Reduce whitespace please. Only add 1 blank line between test cases,
> ------------------------------
>
> In src/utils/parsePhone.ts
> <https://github.com/CovidEngine/vaxxnz/pull/227#discussion_r711912504>:
>
> > +    //Does a standard phone regex, but that will also just return the 0800 from a number like 0800 ORANGA
> +    //So I check its length and do an 0800 regex as well
>
> Small ask to improve the comment, remember other people need to read this
> in the context of what the code does, not what you ("so *I* check") do.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CovidEngine/vaxxnz/pull/227#pullrequestreview-758290402>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM5P7RUCKTHS6J7BX77HSZDUC3LE7ANCNFSM5EKA25XQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-20 09:39 UTC, olafwrieden approved these changes
Looks good to me. @noway can you give it glance too and merge when convenient. Thanks! Closes #167

2021-09-20 12:35 UTC, noway approved these changes
Love it ❤️ . I've added 1 more test from the original issue. All works nicely. Good work  @bookwyrm31415

2021-09-20 12:35 UTC, merged